Social_Network-master /Anti_Social_Freaks/Anti_Social_Freaks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('anti-social/' , include('Social_Network.urls')),


]

Social_Network-master /Anti_Social_Freaks/Social_Network/urls.py
from django .urls import path
from . import views
from django.contrib.auth.views import login,logout


# all add your needed urls here
urlpatterns = [



    # Sign Up, Log in and Log out
    # this is just a test make sure to try this path first to make sure that everyting is ok
    path('login/', login, {'template_name': 'Social_Network/login.html'}),
    path('logout/', logout, {'template_name': 'Social_Network/logout.html'}),
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    path('profile/edit',views.edit_profile,name='edit_profile'),

    path('home',views.home , name='home'), # home page
    path('CommentPost/<int:post_id>/', views.addComment, name='addcomment'), # add a comment for a given post id
    path('LikePost/<int:post_id>/', views.addLike, name='addLike'), # add a Like for a given post id
]

Social_Network-master /Anti_Social_Freaks/Social_Network/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.signals import post_save

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True,)
    mobile=models.CharField(max_length=11)
    about=models.CharField(max_length=500)
    date_of_birth= models.DateField()
    image=models.ImageField(upload_to='profile_image',blank=True)#$$$$$$$$$$$$$$$$$

    def __str__(self):
        return self.user.username

def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user = kwargs['instance'])
post_save.connect(create_profile,sender= User)


class Post(models.Model):# shares is missing $$$$$$$$$$
    publisher = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.CharField(max_length=2000)
    date = models.DateTimeField(blank=True,default=datetime.now)

    def __str__(self):
        return self.content


class Comment(models.Model):
    post=models.ForeignKey(Post, on_delete=models.CASCADE)
    content = models.CharField(max_length=1000)
    commenter = models.ForeignKey(User, on_delete=models.CASCADE ,null=True )

    def __str__(self):
        return self.content


class Like(models.Model):
    liker=models.ForeignKey(User,on_delete=models.CASCADE)
    post=models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return '%s %s %s' % (self.liker, 'Liked', self.post)

Social_Network-master /Anti_Social_Freaks/Social_Network/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from . import models

class RegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username',
             #     'first_name',
              #    'last_name',
                  'password1',
                  'password2'
        )
        #then have to define a function that allows the form to save the data to the model.



    def save(self, commit=True):


        try:
            user = super(RegistrationForm,self).save(commit = False)
#            user.first_name = self.cleaned_data['first_name']
            # cleaned_data--> makes sure that there is no SQL in the data and it's safe to save it.
 #           user.last_name = self.cleaned_data['last_name']


        except ValueError:
            raise forms.ValidationError("This Username is already taken or Password does not match")




        if commit:
            user.save()


class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username',
   #               'profile.mobile',
 #                 'profile.date_of_birth',
#                  'profile.about'
                  'first_name',
                  'last_name',
                  'password'

        )


class postForm(forms.Form):
    post = forms.CharField(max_length=2000)



class commentForm(forms.Form):
    comment = forms.CharField(max_length=1000)

Social_Network-master /Anti_Social_Freaks/Social_Network/views.py
from django.shortcuts import render
from django .http import HttpResponsePermanentRedirect
from .forms import RegistrationForm,EditProfileForm,postForm,commentForm
from django.http import HttpResponse
from django .template import loader
from .models import *
from django.shortcuts import redirect
from django.contrib.auth import logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
# Create your views here.




####################### Log In and Log Out




def register(request):
    if request.method =='POST':

        form = RegistrationForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('/anti-social/login')
    else:
        form= RegistrationForm()

        args={'form':form}
        return render(request,'Social_Network/registration.html',args)





def login_redirect( request ):
    return redirect("/anti-social/home")





def logout_view(request):
    logout(request)
    return render(request,'Social_Network/logout.html')




####################### Log In and Log Out





def home(request): # news feed and posts from other freaks

    if request.method == 'POST':
        # Create a form instance
        post_form = postForm(request.POST)


        if(post_form.is_valid()):
            user_of_post = User.objects.get(id=request.user.id)
            post_of_user = post_form.cleaned_data['post']
            post = Post(publisher=user_of_post , content=post_of_user)
            post.save()



    else:
        post_form = postForm()

    comment_form = commentForm()
    posts = Post.objects.exclude(publisher=request.user)
    context = {
        'post_form': post_form,
        'comment_form': comment_form,
        'posts': posts
    }

    return render(request, 'Social_Network/home.html', context)

def view_profile(request):
    args={'user': request.user}
    return render(request,'Social_Network/profile.html',args)

def edit_profile(request):
    if request.method == 'POST':
        form= EditProfileForm(request.POST ,instance= request.user)
        if form.is_valid():
            form.save()
            return redirect('/anti-social/profile')
    else:
        form = EditProfileForm(instance= request.user)
        args = {'form': form}
        return render(request , 'Social_Network/edit_profile.html',args)


def addComment(request,post_id):
    comment_form = commentForm(request.POST)

    if (comment_form.is_valid()):
        user_of_comment = User.objects.get(id=request.user.id)
        post_of_comment = Post.objects.get(id=post_id)
        comment_of_post = comment_form.cleaned_data['comment']
        comment = Comment(post=post_of_comment,content=comment_of_post,commenter=user_of_comment)
        comment.save()

    return redirect('home')




def addLike(request,post_id):

    user_of_like = User.objects.get(id=request.user.id)
    post_of_like = Post.objects.get(id=post_id)
    like = Like(post=post_of_like,liker=user_of_like)
    like.save()
    return redirect('home')

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/edit_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
</head>
<h1>Edit Your Profile FREAKY !!</h1>
<body>
<div class="container">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"> Submit </button>
    </form>
</div>


</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home page</title>
</head>
<body>


Hello {{user.first_name}} Freaky {{user.last_name}}!!
<form>
    <button type="submit" formaction="/anti-social/profile/">MyProfile</button>
</form>
<form>
    <button type="submit" formaction="/anti-social/logout/">Logout</button>
</form>



<h3>Write a Post</h3>
<form method="post">
    {% csrf_token %}
    {{ post_form }}
    <input type = "submit" value="Write" />

</form>


<br> <br>


<h4>
    Posts by other Freaks
</h4>

<ul>
{% for post in posts %}

    <li>{{ post.content }} <br> by: {{ post.publisher.username }} <br> at: {{ post.date }}

    <br>

<form method="post"  action="LikePost/{{ post.id }}/ ">
    {% csrf_token %}
    <input type = "submit" value="Like" />

</form>

    Likes {{    post.like_set.count }} <br>


    Comments <br>
    {% for comment in post.comment_set.all %}
        <li>

        {{comment.content }} by {{ comment.commenter.username }}

        </li>


        {% endfor %}




    Write a Comment
<form method="post"  action="CommentPost/{{ post.id }}/ ">
    {% csrf_token %}
    {{ comment_form }}
    <input type = "submit" value="Comment" />

</form>




    </li>

    <br> <br> <br>

    {% endfor %}
</ul>


</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Login </title>
</head>
<body>
 <div class="container">
    <h1> WELCOME </h1>
    <p>
    You can login from here...Mr/Freak.
    </p>
    <h2>login</h2>
    <form method="post">
    {% csrf_token%}
    {{ form.as_p }}
    <button type="submit">Login</button>
    </form>
     <form>
         <button type="submit" formaction="/anti-social/register/">Register</button>
     </form>

 </div>
</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Logged out </title>
</head>
<body>
 <div class="container">
    <h1> BYE </h1>
    <p>
    You've logged out...you're not Mr/Freak anymore!!
    </p>
     <form method="post">
    {% csrf_token%}
    {{ form.as_p }}
    <button type="submit" formaction="/anti-social/login/">Login</button>
    </form>
 </div>
</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>My Profile</title>
</head>
<h1>Your Profile FREAKY ;D</h1>
<body>
<div class="container">
    <p>
        {{user.username}}<br><br>

        {{user.profile.about}} <br><br>

        {{user.profile.date_of_birth}} <br><br>

        {{user.profile.mobile}}
    </p>

</div>
<form>
         <button type="submit" formaction="/anti-social/profile/edit">Edit</button>
</form>

</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/registration.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Register </title>
</head>
<body>
 <div class="container">
    <h1>Register</h1>
    <form method="post">
    {% csrf_token%}
    {{ form.as_p }}
    <button type="submit">sign up</button>
    </form>
 </div>
</body>
</html>

Social_Network-master /Anti_Social_Freaks/Social_Network/templates/Social_Network/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home page</title>
</head>
<body>


<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type = "submit" value="Submit" />

</form>


</body>
</html>